### ISSUE TITLE
How to load standard JS methods in?

### ISSUE THREAD

**Issue by tyvdh** [apiaryio/pitboss#19]
Trying to run a very basic setTimeout function but: 
`VM Runtime Error: ReferenceError: setTimeout is not defined`

I would have thought I could load it into the context but that seems to only accept basic JSON type strings and objects. How would I get things like setTimeout into the vm?

**Comment by kuba-kubula** [comment]
@tyvdh the question is: Why would you need `setTimeout`, since setTimeout can lead to various vulnerabilities regarding memory, event-loop and stuff.

Also asynchronous code is not allowed in `pitboss-ng` exactly because of that.
Pitboss-ng uses `vm2` ( https://www.npmjs.com/package/vm2 )  sychronous function to execute code.
